-- ATP Suplementos: historial profesional de movimientos de stock
create table if not exists public.atp_stock_movements (
  id bigint generated by default as identity primary key,
  product_id text not null,
  product_name text not null default '',
  movement_type text not null check (movement_type in ('sale','restock','correction','gift','initial','other')),
  quantity_change integer not null check (quantity_change <> 0),
  stock_before integer not null,
  stock_after integer not null check (stock_after >= 0),
  reason text not null default '',
  order_id uuid references public.atp_orders(id) on delete set null,
  order_number text,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid()
);
create index if not exists atp_stock_movements_product_idx on public.atp_stock_movements(product_id,created_at desc);
create index if not exists atp_stock_movements_created_idx on public.atp_stock_movements(created_at desc);
alter table public.atp_stock_movements enable row level security;
drop policy if exists "ATP stock admin leer" on public.atp_stock_movements;
create policy "ATP stock admin leer" on public.atp_stock_movements for select to authenticated using(true);
drop policy if exists "ATP stock admin insertar" on public.atp_stock_movements;
create policy "ATP stock admin insertar" on public.atp_stock_movements for insert to authenticated with check(true);
drop policy if exists "ATP stock admin eliminar" on public.atp_stock_movements;
create policy "ATP stock admin eliminar" on public.atp_stock_movements for delete to authenticated using(true);
grant delete on table public.atp_stock_movements to authenticated;

create or replace function public.atp_adjust_product_stock(p_product_id text,p_new_stock integer,p_movement_type text,p_reason text default '')
returns jsonb language plpgsql security definer set search_path=public as $$
declare p public.atp_products; delta integer;
begin
 if p_new_stock < 0 then raise exception 'El stock no puede ser negativo'; end if;
 select * into p from public.atp_products where id=p_product_id for update;
 if p.id is null then raise exception 'Producto no encontrado'; end if;
 delta:=p_new_stock-coalesce(p.stock,0);
 if delta=0 then return jsonb_build_object('ok',true,'changed',false); end if;
 update public.atp_products set stock=p_new_stock,updated_at=now() where id=p_product_id;
 insert into public.atp_stock_movements(product_id,product_name,movement_type,quantity_change,stock_before,stock_after,reason)
 values(p.id,p.name,case when p_movement_type in ('sale','restock','correction','gift','initial','other') then p_movement_type else 'other' end,delta,p.stock,p_new_stock,coalesce(p_reason,''));
 return jsonb_build_object('ok',true,'changed',true,'stock',p_new_stock);
end $$;
grant execute on function public.atp_adjust_product_stock(text,integer,text,text) to authenticated;

create or replace function public.atp_process_approved_order(p_external_reference text, p_payment_id text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare o public.atp_orders; item jsonb; c public.atp_customers; pts integer; clean_phone text; p public.atp_products; qty integer; next_stock integer;
begin
 select * into o from public.atp_orders where external_reference=p_external_reference for update;
 if o.id is null then return jsonb_build_object('ok',false,'reason','not_found'); end if;
 if o.stock_processed then return jsonb_build_object('ok',true,'already_processed',true,'tracking_code',o.tracking_code); end if;
 for item in select value from jsonb_array_elements(o.items) loop
   qty:=greatest(0,coalesce((item->>'quantity')::integer,0));
   select * into p from public.atp_products where id=item->>'id' for update;
   if p.id is not null and qty>0 then
     next_stock:=greatest(0,p.stock-qty);
     update public.atp_products set stock=next_stock,updated_at=now() where id=p.id;
     insert into public.atp_stock_movements(product_id,product_name,movement_type,quantity_change,stock_before,stock_after,reason,order_id,order_number)
     values(p.id,p.name,'sale',next_stock-p.stock,p.stock,next_stock,'Venta confirmada',o.id,coalesce(o.order_number::text,o.tracking_code));
   end if;
 end loop;
 clean_phone:=regexp_replace(coalesce(o.customer->>'phone',''),'[^0-9]','','g'); pts:=floor(o.total/1000)::integer;
 insert into public.atp_customers(phone,name,email,tax_id,orders_count,total_spent,points_balance,lifetime_points,last_order_at,is_active,deleted_at)
 values(clean_phone,coalesce(o.customer->>'name',''),coalesce(o.customer->>'email',''),regexp_replace(coalesce(o.customer->>'tax_id',''),'[^0-9]','','g'),1,o.total,pts,pts,now(),true,null)
 on conflict(phone) do update set name=excluded.name,email=case when excluded.email<>'' then excluded.email else atp_customers.email end,tax_id=case when excluded.tax_id<>'' then excluded.tax_id else atp_customers.tax_id end,orders_count=atp_customers.orders_count+1,total_spent=atp_customers.total_spent+excluded.total_spent,points_balance=atp_customers.points_balance+excluded.points_balance,lifetime_points=atp_customers.lifetime_points+excluded.lifetime_points,last_order_at=now(),is_active=true,deleted_at=null,updated_at=now() returning * into c;
 update public.atp_coupons set used_count=used_count+1,updated_at=now() where code=o.coupon and o.coupon<>'';
 update public.atp_orders set payment_status='approved',status='pago_confirmado',mp_payment_id=p_payment_id,stock_processed=true,points_awarded=pts,customer_id=c.id,tracking_code=coalesce(tracking_code,'ATP-'||upper(substr(replace(id::text,'-',''),1,8))),updated_at=now() where id=o.id;
 return jsonb_build_object('ok',true,'points',pts,'tracking_code',coalesce(o.tracking_code,'ATP-'||upper(substr(replace(o.id::text,'-',''),1,8))));
end $$;
