let products=[],settings={};
const CATEGORIES=["Proteínas","Creatinas","Pre-entrenos","Aminoácidos","Vitaminas","Quemadores","Ganadores","Shakers","Accesorios"];
const money=v=>new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0}).format(v);
function toastMsg(t){adminToast.textContent=t;adminToast.classList.add("show");setTimeout(()=>adminToast.classList.remove("show"),1800)}
async function loadData(){[products,settings]=await Promise.all([ATPData.getProducts({includeInactive:true}),ATPData.getSettings()]);renderAll()}
async function login(){loginScreen.classList.add("hidden");adminApp.classList.remove("hidden");modeBadge.textContent=ATPData.mode==="supabase"?"Conectado a Supabase":"Modo local";await loadData()}
loginForm.onsubmit=async e=>{e.preventDefault();loginError.textContent="";try{await ATPData.signIn(emailInput.value,passwordInput.value);await login()}catch(err){loginError.textContent=err.message||"No se pudo iniciar sesión."}};
(async()=>{try{if(await ATPData.getSession())await login()}catch(err){console.error(err)}})();
logoutBtn.onclick=async()=>{await ATPData.signOut();location.reload()};
document.querySelectorAll(".nav-link").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav-link").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));document.getElementById(`${b.dataset.view}View`).classList.add("active");viewTitle.textContent=b.textContent;newProductTop.style.display=b.dataset.view==="products"?"block":"none"});
function renderDashboard(){statProducts.textContent=products.length;statStock.textContent=products.reduce((a,p)=>a+Number(p.stock||0),0);statOut.textContent=products.filter(p=>Number(p.stock)<=0).length;statValue.textContent=money(products.reduce((a,p)=>a+Number(p.stock||0)*Number(p.price||0),0));const low=[...products].sort((a,b)=>a.stock-b.stock).slice(0,6);lowStockList.innerHTML=low.map(p=>`<div class="simple-row"><div><b>${p.name}</b><span>${p.brand}</span></div><span>${p.stock} unidades</span></div>`).join("")}
function renderTable(){const q=adminSearch.value.trim().toLowerCase();const list=products.filter(p=>`${p.name} ${p.brand} ${p.category}`.toLowerCase().includes(q));productTable.innerHTML=list.map(p=>`<tr><td><b>${p.name}</b><small>${p.brand}</small></td><td>${p.category}</td><td>${money(p.price)}</td><td>${p.stock}</td><td><span class="status ${!p.active||p.stock<=0?"out":""}">${!p.active?"Oculto":p.stock<=0?"Sin stock":"Disponible"}</span></td><td><div class="row-actions"><button data-edit="${p.id}">Editar</button><button class="delete" data-delete="${p.id}">Eliminar</button></div></td></tr>`).join("");productTable.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openProduct(b.dataset.edit));productTable.querySelectorAll("[data-delete]").forEach(b=>b.onclick=async()=>{if(confirm("¿Eliminar este producto?")){try{await ATPData.deleteProduct(b.dataset.delete);await loadData();toastMsg("Producto eliminado")}catch(err){alert(err.message)}}})}
function renderSettings(){Object.entries(settings).forEach(([k,v])=>{if(settingsForm.elements[k])settingsForm.elements[k].value=v||""})}
function renderAll(){renderDashboard();renderTable();renderSettings()}
function openProduct(id=""){productForm.reset();productForm.elements.category.innerHTML=CATEGORIES.map(c=>`<option>${c}</option>`).join("");modalTitle.textContent=id?"Editar producto":"Nuevo producto";productForm.elements.active.checked=true;if(id){const p=products.find(x=>x.id===id);Object.entries(p).forEach(([k,v])=>{const el=productForm.elements[k];if(!el)return;if(el.type==="checkbox")el.checked=Boolean(v);else if(k==="flavors"&&Array.isArray(v))el.value=v.join(", ");else el.value=v??""})}modal.classList.add("open")}
function closeProduct(){modal.classList.remove("open")}newProductTop.onclick=()=>openProduct();newProductBtn.onclick=()=>openProduct();modalClose.onclick=closeProduct;cancelProduct.onclick=closeProduct;
productForm.onsubmit=async e=>{e.preventDefault();const fd=new FormData(productForm);const oldId=fd.get("id");const id=oldId||`${Date.now()}`;let image=fd.get("image").trim();try{const file=imageFile.files[0];if(file){toastMsg("Subiendo imagen...");image=await ATPData.uploadProductImage(file,id)}const item={id,name:fd.get("name").trim(),brand:fd.get("brand").trim(),category:fd.get("category"),price:Number(fd.get("price")),stock:Number(fd.get("stock")),detail:fd.get("detail").trim(),tag:fd.get("tag").trim(),image,gallery:[],presentation:fd.get("presentation").trim(),flavors:fd.get("flavors").split(",").map(x=>x.trim()).filter(Boolean),description:fd.get("description").trim(),ingredients:fd.get("ingredients").trim(),nutrition:fd.get("nutrition").trim(),featured:productForm.elements.featured.checked,active:productForm.elements.active.checked};await ATPData.saveProduct(item);await loadData();closeProduct();toastMsg("Producto guardado")}catch(err){alert(err.message||"No se pudo guardar.")}};
adminSearch.oninput=renderTable;
settingsForm.onsubmit=async e=>{e.preventDefault();try{settings=Object.fromEntries(new FormData(settingsForm).entries());await ATPData.saveSettings(settings);await loadData();toastMsg("Configuración guardada")}catch(err){alert(err.message)}};
exportBtn.onclick=()=>{const blob=new Blob([JSON.stringify({products,settings},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="atp-suplementos-backup.json";a.click();URL.revokeObjectURL(a.href)};
importBtn.onclick=()=>toastMsg("La importación masiva se hará en la próxima versión.");
resetBtn.onclick=()=>toastMsg("Restablecimiento desactivado en modo online.");