let products=[],settings={},orders=[],customers=[],coupons=[];
const CATEGORIES=['Proteínas','Creatinas','Pre-entrenos','Aminoácidos','Vitaminas','Quemadores','Ganadores','Shakers','Accesorios'];
const money=v=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(v||0);
function toastMsg(t){adminToast.textContent=t;adminToast.classList.add('show');setTimeout(()=>adminToast.classList.remove('show'),1800)}
async function loadData(){[products,settings,orders,customers,coupons]=await Promise.all([ATPData.getProducts({includeInactive:true}),ATPData.getSettings(),ATPData.getOrders(),ATPData.getCustomers(),ATPData.getCoupons()]);renderAll()}
async function login(){loginScreen.classList.add('hidden');adminApp.classList.remove('hidden');modeBadge.textContent='Conectado a Supabase';await loadData()}
loginForm.onsubmit=async e=>{e.preventDefault();loginError.textContent='';try{await ATPData.signIn(emailInput.value,passwordInput.value);await login()}catch(err){loginError.textContent=err.message||'No se pudo iniciar sesión.'}};
(async()=>{try{if(await ATPData.getSession())await login()}catch(err){console.error(err)}})(); logoutBtn.onclick=async()=>{await ATPData.signOut();location.reload()};
document.querySelectorAll('.nav-link').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-link').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(`${b.dataset.view}View`).classList.add('active');viewTitle.textContent=b.textContent;newProductTop.style.display=b.dataset.view==='products'?'block':'none'});
function renderDashboard(){const paid=orders.filter(o=>o.payment_status==='approved');statProducts.textContent=products.length;statStock.textContent=products.reduce((a,p)=>a+Number(p.stock||0),0);statOut.textContent=products.filter(p=>Number(p.stock)<=0).length;statSales.textContent=money(paid.reduce((a,o)=>a+Number(o.total||0),0));statPaid.textContent=paid.length;statCustomers.textContent=customers.length;statPoints.textContent=customers.reduce((a,c)=>a+Number(c.points_balance||0),0);const low=[...products].sort((a,b)=>a.stock-b.stock).slice(0,8);lowStockList.innerHTML=low.map(p=>`<div class="simple-row"><div><b>${p.name}</b><span>${p.brand}</span></div><span class="${p.stock<=3?'metric-positive':''}">${p.stock} unidades</span></div>`).join('')||'<p>Sin productos.</p>'}
function renderTable(){const q=adminSearch.value.trim().toLowerCase();const list=products.filter(p=>`${p.name} ${p.brand} ${p.category}`.toLowerCase().includes(q));productTable.innerHTML=list.map(p=>`<tr><td><b>${p.name}</b><small>${p.brand}</small></td><td>${p.category}</td><td>${money(p.price)}</td><td>${p.stock}</td><td><span class="status ${!p.active||p.stock<=0?'out':''}">${!p.active?'Oculto':p.stock<=0?'Sin stock':'Disponible'}</span></td><td><div class="row-actions"><button data-edit="${p.id}">Editar</button><button class="delete" data-delete="${p.id}">Eliminar</button></div></td></tr>`).join('');productTable.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openProduct(b.dataset.edit));productTable.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(confirm('¿Eliminar este producto?')){await ATPData.deleteProduct(b.dataset.delete);await loadData();toastMsg('Producto eliminado')}})}
function renderSettings(){Object.entries(settings).forEach(([k,v])=>{if(settingsForm.elements[k])settingsForm.elements[k].value=v||''})}
function renderOrders(){const q=(orderSearch.value||'').trim().toLowerCase(),sf=orderStatusFilter.value||'';const list=orders.filter(o=>{const text=`${o.id} ${o.tracking_code||''} ${o.customer?.name||''} ${o.customer?.phone||''} ${o.coupon||''}`.toLowerCase();return(!q||text.includes(q))&&(!sf||o.status===sf)});const states=['nuevo','esperando_pago','pagado','preparando','listo','en_camino','entregado','cancelado','pago_rechazado'];orderTable.innerHTML=list.map(o=>`<tr><td><b>#${o.tracking_code||String(o.id).slice(0,8)}</b><small class="order-items">${(o.items||[]).map(x=>`${x.quantity}× ${x.name||'Producto'}`).join(' · ')}</small></td><td><b>${o.customer?.name||'Sin nombre'}</b><small>${o.customer?.phone||''}</small></td><td>${o.delivery_method==='retiro'?'Retiro':'Envío'}</td><td><b>${money(o.total)}</b><small>${o.coupon?`${o.coupon} · -${money(o.discount)}`:'Sin cupón'}</small></td><td><span class="status ${o.payment_status!=='approved'?'out':''}">${o.channel==='transferencia'?(o.payment_status==='approved'?'Transferencia acreditada':'Esperando transferencia'):(o.payment_status||'pending')}</span></td><td><select class="order-status" data-order="${o.id}">${states.map(x=>`<option ${x===o.status?'selected':''}>${x}</option>`).join('')}</select></td><td>${new Date(o.created_at).toLocaleString('es-AR')}</td></tr>`).join('');orderTable.querySelectorAll('[data-order]').forEach(el=>el.onchange=async()=>{const order=orders.find(o=>String(o.id)===String(el.dataset.order));if(order?.channel==='transferencia'&&el.value==='pagado'&&order.payment_status!=='approved'){if(!confirm('¿Confirmás que la transferencia está acreditada? Esto descontará stock y sumará ATP Points.')){renderOrders();return}const{data,error}=await ATPData.client.rpc('atp_process_approved_order',{p_external_reference:order.external_reference,p_payment_id:`TRANSFER-${Date.now()}`});if(error)throw error}else await ATPData.updateOrder(el.dataset.order,{status:el.value});await loadData();toastMsg('Estado actualizado')})}
function renderCustomers(){const q=(customerSearch.value||'').trim().toLowerCase();const list=customers.filter(c=>`${c.name} ${c.phone} ${c.email||''}`.toLowerCase().includes(q));customerTable.innerHTML=list.map(c=>`<tr><td><b>${c.name||'Sin nombre'}</b><small>Cliente desde ${new Date(c.created_at).toLocaleDateString('es-AR')}</small></td><td>${c.phone||''}<small>${c.email||''}</small></td><td>${c.orders_count||0}</td><td>${money(c.total_spent)}</td><td><b class="metric-positive">${c.points_balance||0}</b></td><td>${c.last_order_at?new Date(c.last_order_at).toLocaleString('es-AR'):'-'}</td></tr>`).join('')}
function renderCoupons(){couponTable.innerHTML=coupons.map(c=>`<tr><td><b>${c.code}</b></td><td>${c.discount_percent}%</td><td>${c.used_count||0}${c.max_uses?` / ${c.max_uses}`:''}</td><td>${c.expires_at?new Date(c.expires_at+'T12:00:00').toLocaleDateString('es-AR'):'Sin vencimiento'}</td><td><span class="status ${!c.active?'out':''}">${c.active?'Activo':'Inactivo'}</span></td><td><button class="delete" data-coupon="${c.code}">Eliminar</button></td></tr>`).join('');couponTable.querySelectorAll('[data-coupon]').forEach(b=>b.onclick=async()=>{if(confirm(`¿Eliminar ${b.dataset.coupon}?`)){await ATPData.deleteCoupon(b.dataset.coupon);await loadData();toastMsg('Cupón eliminado')}})}
function renderAll(){renderDashboard();renderTable();renderSettings();renderOrders();renderCustomers();renderCoupons()}
function openProduct(id=''){productForm.reset();productForm.elements.category.innerHTML=CATEGORIES.map(c=>`<option>${c}</option>`).join('');modalTitle.textContent=id?'Editar producto':'Nuevo producto';productForm.elements.active.checked=true;if(id){const p=products.find(x=>x.id===id);Object.entries(p).forEach(([k,v])=>{const el=productForm.elements[k];if(!el)return;if(el.type==='checkbox')el.checked=Boolean(v);else if(k==='flavors'&&Array.isArray(v))el.value=v.join(', ');else el.value=v??''})}modal.classList.add('open')}
function closeProduct(){modal.classList.remove('open')} newProductTop.onclick=()=>openProduct();newProductBtn.onclick=()=>openProduct();modalClose.onclick=closeProduct;cancelProduct.onclick=closeProduct;
productForm.onsubmit=async e=>{e.preventDefault();const fd=new FormData(productForm),oldId=fd.get('id'),id=oldId||`${Date.now()}`;let image=fd.get('image').trim();try{const file=imageFile.files[0];if(file){toastMsg('Subiendo imagen...');image=await ATPData.uploadProductImage(file,id)}await ATPData.saveProduct({id,name:fd.get('name').trim(),brand:fd.get('brand').trim(),category:fd.get('category'),price:Number(fd.get('price')),stock:Number(fd.get('stock')),detail:fd.get('detail').trim(),tag:fd.get('tag').trim(),image,gallery:[],presentation:fd.get('presentation').trim(),flavors:fd.get('flavors').split(',').map(x=>x.trim()).filter(Boolean),description:fd.get('description').trim(),ingredients:fd.get('ingredients').trim(),nutrition:fd.get('nutrition').trim(),featured:productForm.elements.featured.checked,active:productForm.elements.active.checked});await loadData();closeProduct();toastMsg('Producto guardado')}catch(err){alert(err.message||'No se pudo guardar.')}};
adminSearch.oninput=renderTable;orderSearch.oninput=renderOrders;orderStatusFilter.onchange=renderOrders;customerSearch.oninput=renderCustomers;
settingsForm.onsubmit=async e=>{e.preventDefault();settings=Object.fromEntries(new FormData(settingsForm).entries());await ATPData.saveSettings(settings);await loadData();toastMsg('Configuración guardada')};
couponForm.onsubmit=async e=>{e.preventDefault();const fd=new FormData(couponForm);await ATPData.saveCoupon({code:fd.get('code'),discount_percent:fd.get('discount_percent'),max_uses:fd.get('max_uses'),expires_at:fd.get('expires_at'),active:couponForm.elements.active.checked});couponForm.reset();couponForm.elements.active.checked=true;await loadData();toastMsg('Cupón guardado')};
exportBtn.onclick=()=>{const blob=new Blob([JSON.stringify({products,settings,orders,customers,coupons},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='atp-suplementos-backup.json';a.click();URL.revokeObjectURL(a.href)};importBtn.onclick=()=>toastMsg('Importación no habilitada.');resetBtn.onclick=()=>toastMsg('Restablecimiento desactivado.');
