const money=v=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(v);const cart=JSON.parse(localStorage.getItem('atp_cart')||'{}');let products=[],coupons={},appliedCoupon='';
function showToast(m){toast.textContent=m;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)} function entries(){return Object.entries(cart).filter(([id])=>products.some(p=>String(p.id)===String(id)))}
function totals(){const subtotalValue=entries().reduce((sum,[id,q])=>{const p=products.find(x=>String(x.id)===String(id));return sum+Number(p.price)*Number(q)},0),percent=Number(coupons[appliedCoupon]||0),discountValue=Math.round(subtotalValue*percent)/100;return{subtotal:subtotalValue,discount:discountValue,total:Math.max(0,subtotalValue-discountValue)}}
function renderSummary(){const list=entries();if(!list.length){location.replace('index.html');return}orderItems.innerHTML=list.map(([id,q])=>{const p=products.find(x=>String(x.id)===String(id));return`<div class="order-item"><div><h3>${q} × ${p.name}</h3><small>${p.brand||'ATP Suplementos'}</small></div><b>${money(Number(p.price)*Number(q))}</b></div>`}).join('');const t=totals();subtotal.textContent=money(t.subtotal);discount.textContent=`-${money(t.discount)}`;total.textContent=money(t.total);discountRow.classList.toggle('visible',t.discount>0)}
function validCustomer(show=false){const name=customerName.value.trim(),phone=customerPhone.value.replace(/\D/g,''),okName=name.length>=3,okPhone=phone.length>=8;customerName.classList.toggle('invalid',show&&!okName);customerPhone.classList.toggle('invalid',show&&!okPhone);customerError.textContent=show&&(!okName||!okPhone)?'Completá un nombre válido y un teléfono de al menos 8 números.':'';const ok=okName&&okPhone;couponCard.classList.toggle('locked',!ok);couponInput.disabled=!ok;applyCouponBtn.disabled=!ok;mercadoPagoBtn.disabled=!ok;return ok}
function applyCoupon(){if(!validCustomer(true))return;const code=couponInput.value.trim().toUpperCase();if(!code){appliedCoupon='';couponMessage.textContent='';renderSummary();return}if(!coupons[code]){appliedCoupon='';couponMessage.textContent='Código inválido, vencido o sin usos disponibles.';renderSummary();return}appliedCoupon=code;couponInput.value=code;couponMessage.textContent=`${code}: ${coupons[code]}% de descuento aplicado.`;renderSummary()}
customerName.addEventListener('input',()=>validCustomer(false));customerPhone.addEventListener('input',()=>validCustomer(false));applyCouponBtn.onclick=applyCoupon;couponInput.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();applyCoupon()}});
checkoutForm.addEventListener('submit',async e=>{e.preventDefault();if(!validCustomer(true))return;const list=entries();if(!list.length)return showToast('El carrito está vacío');const original=mercadoPagoBtn.textContent;mercadoPagoBtn.disabled=true;mercadoPagoBtn.textContent='Preparando pago...';try{const deliveryMethod=document.querySelector('input[name="delivery"]:checked').value,response=await fetch('/api/create-preference',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:list.map(([id,quantity])=>({id,quantity})),coupon:appliedCoupon,deliveryMethod,customer:{name:customerName.value.trim(),phone:customerPhone.value.trim(),email:customerEmail.value.trim()}})}),data=await response.json();if(!response.ok)throw new Error(data.error||'No se pudo iniciar el pago.');sessionStorage.setItem('atp_last_order',JSON.stringify({orderId:data.orderId,trackingCode:data.trackingCode}));location.href=data.checkoutUrl}catch(err){showToast(err.message);mercadoPagoBtn.disabled=false;mercadoPagoBtn.textContent=original}});
(async()=>{try{[products]=await Promise.all([ATPData.getProducts()]);const{data,error}=await ATPData.client.from('atp_coupons').select('code,discount_percent,max_uses,used_count,expires_at').eq('active',true);if(error)throw error;const today=new Date().toISOString().slice(0,10);(data||[]).filter(c=>(!c.expires_at||c.expires_at>=today)&&(!c.max_uses||c.used_count<c.max_uses)).forEach(c=>coupons[c.code]=Number(c.discount_percent));renderSummary();validCustomer(false)}catch(err){console.error(err);showToast('No se pudo cargar el checkout.')}})();
