-- ATP Suplementos — historial real y permanente de movimientos de stock
-- Ejecutar TODO este archivo una sola vez en Supabase > SQL Editor > Run.
-- Está adaptado a las tablas reales del proyecto: products, orders, store_settings.

create table if not exists public.stock_movements (
  id bigint generated by default as identity primary key,
  product_id text not null,
  product_name text not null default '',
  movement_type text not null default 'other'
    check (movement_type in ('sale','restock','correction','gift','initial','other')),
  quantity_change integer not null check (quantity_change <> 0),
  stock_before integer not null default 0,
  stock_after integer not null default 0 check (stock_after >= 0),
  reason text not null default '',
  order_id text,
  order_number text,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid()
);

create index if not exists stock_movements_product_date_idx
  on public.stock_movements(product_id, created_at desc);
create index if not exists stock_movements_date_idx
  on public.stock_movements(created_at desc);

alter table public.stock_movements enable row level security;

drop policy if exists "Stock admin leer" on public.stock_movements;
create policy "Stock admin leer"
  on public.stock_movements for select
  to authenticated using (true);

drop policy if exists "Stock admin insertar" on public.stock_movements;
create policy "Stock admin insertar"
  on public.stock_movements for insert
  to authenticated with check (true);

drop policy if exists "Stock admin eliminar" on public.stock_movements;
create policy "Stock admin eliminar"
  on public.stock_movements for delete
  to authenticated using (true);

grant select, insert, delete on public.stock_movements to authenticated;
grant usage, select on sequence public.stock_movements_id_seq to authenticated;

-- Agrega updated_at si la tabla products todavía no lo tiene.
alter table public.products
  add column if not exists updated_at timestamptz not null default now();

-- Supabase debe mostrar: Success. No rows returned.
